
```{r}
library(XML)
library(RCurl)


fp <- "Books-v3.xml"

xmlDocument = xmlParse(fp)
r = xmlRoot(xmlDocument)
```

## Query 1

<h4> What is the title of the book written by "Galos, Mike"?List the titles and the prices. </h4>

```{r}
# QUERY 1 - What is the title of the book written by "Galos, Mike"List the titles and the prices.?
bookname = xpathSApply(xmlDocument,'//catalog/book[author="Galos, Mike"]/title/text()| //catalog/book[author="Galos, Mike"]/price/text()', xmlValue)
bookname
```


### Query 2

<h4> In what genre is the book with id "bk109". </h4>

```{r}
#QUERY 2 - In what genre is the book with id "bk109".
bookgenre = xpathSApply(xmlDocument,'//book[@id = "bk109"]/genre/text()', xmlValue)
bookgenre
```


### Query 3


<h4>What are the titles of the books that sell for the lowest price?</h4>
```{r} 
#QUERY 3 - What are the titles of the books that sell for the lowest price?
dfdate = xpathSApply(xmlDocument,'//book[price =min(//book/price)]/title', xmlValue)
dfdate
```





### Query 4
<h4>List the title and prices of all books in the "Computer" genre.</h4>

```{r}
#QUERY 4 - List the title and prices of all books in the "Computer" genre.
titleprice = xpathSApply(xmlDocument,'//book[genre = "Computer"]/title/text() | //book[genre = "Computer"]/price/text()', xmlValue)
titleprice
```






### Query 5

<h4>What is the number of all books that cost less than $5?.</h4>
```{r}
#QUERY 5 - What is the number of all books that cost less than $5?.
lessthanfive = xpathSApply(xmlDocument,'count(//book[price < 5])', xmlValue)
lessthanfive
```

